### status
GET http://127.0.0.1:3000/status HTTP/1.1


### List articles
GET http://127.0.0.1:3000/articles HTTP/1.1

### Get article
GET http://127.0.0.1:3000/articles/2 HTTP/1.1

### Update article
PUT http://127.0.0.1:3000/articles/2 HTTP/1.1
content-type: application/json

{
    "title": "Test",
}

### Delete article
DELETE http://127.0.0.1:3000/articles/2 HTTP/1.1

### Create article
POST http://127.0.0.1:3000/articles HTTP/1.1
content-type: application/json

{
    "user_id": 2,
    "title": "consectetur",
    "slug": "consectetur"
}

### Panic
GET http://127.0.0.1:3000/panic HTTP/1.1
