### Get root
GET http://127.0.0.1:3000/ HTTP/1.1

### Get article
GET http://127.0.0.1:3000/articles/c2826d515789a42a HTTP/1.1

### Get articles
GET http://127.0.0.1:3000/articles HTTP/1.1

### Create article
POST http://127.0.0.1:3000/articles HTTP/1.1
content-type: application/json

{
    "text": "lorem ipsum"
}

### Update article
PUT http://127.0.0.1:3000/articles/2fc7737544ca5db9 HTTP/1.1
content-type: application/json

{
    "text": "dolor sit amet"
}

### Delee article
DELETE http://127.0.0.1:3000/articles/57f6ff508ef27927 HTTP/1.1
content-type: application/json
